CREATE TABLE [dbo].[tblDiscoveryRequestImport$] (
    [isNewRequest]       FLOAT (53)     NULL,
    [SalesRepName]       NVARCHAR (255) NULL,
    [SalesRepEmail]      NVARCHAR (255) NULL,
    [idOnboardingPhase]  FLOAT (53)     NULL,
    [District]           NVARCHAR (255) NULL,
    [PFDistrict]         NVARCHAR (255) NULL,
    [Onboarding Phase]   NVARCHAR (255) NULL,
    [CustomerName]       NVARCHAR (255) NULL,
    [Eloqua Name]        NVARCHAR (255) NULL,
    [Address]            NVARCHAR (255) NULL,
    [City]               NVARCHAR (255) NULL,
    [State]              NVARCHAR (255) NULL,
    [Zipcode]            NVARCHAR (255) NULL,
    [Country]            NVARCHAR (255) NULL,
    [Commodity]          NVARCHAR (255) NULL,
    [ProjectedRevenue]   FLOAT (53)     NULL,
    [CustomerITContact]  NVARCHAR (255) NULL,
    [CustomerITTitle]    NVARCHAR (255) NULL,
    [CustomerITEmail]    NVARCHAR (255) NULL,
    [CustomerITPhone]    NVARCHAR (255) NULL,
    [EloquaCustoms]      NVARCHAR (255) NULL,
    [ProposedCustoms]    NVARCHAR (255) NULL,
    [CreatedOn]          DATETIME       NULL,
    [ActiveFlag]         FLOAT (53)     NULL,
    [SalesComments]      NVARCHAR (255) NULL,
    [idITBA]             FLOAT (53)     NULL,
    [IT BA]              NVARCHAR (255) NULL,
    [idShippingChannel]  FLOAT (53)     NULL,
    [Shipping Channel]   NVARCHAR (255) NULL,
    [Target Go-Live]     DATETIME       NULL,
    [Actual Go-Live]     DATETIME       NULL,
    [SolutionSummary]    NVARCHAR (255) NULL,
    [idDiscoveryRequest] FLOAT (53)     NULL,
    [TimeSpent]          FLOAT (53)     NULL,
    [FirstSvc]           NVARCHAR (255) NULL
);

