CREATE TABLE [dbo].[tblDiscoveryRequestDetails] (
    [idRequestDetails]          INT           IDENTITY (1, 1) NOT NULL,
    [idRequest]                 INT           NOT NULL,
    [CourierAcctNbr]            VARCHAR (25)  NULL,
    [CourierPinPrefix]          VARCHAR (25)  NULL,
    [CourierContractNbr]        VARCHAR (25)  NULL,
    [CourierTransitDays]        INT           NULL,
    [CourierInductionAddress]   VARCHAR (255) NULL,
    [CourierInductionCity]      VARCHAR (255) NULL,
    [CourierInductionState]     VARCHAR (255) NULL,
    [CourierInductionZip]       VARCHAR (25)  NULL,
    [CourierInductionCountry]   VARCHAR (25)  NULL,
    [CourierFTPusername]        VARCHAR (255) NULL,
    [CourierFTPpwd]             VARCHAR (255) NULL,
    [CourierFTPsenderID]        VARCHAR (255) NULL,
    [LTLAcctNbr]                VARCHAR (25)  NULL,
    [LTLMinProNbr]              VARCHAR (50)  NULL,
    [LTLMaxProNbr]              VARCHAR (50)  NULL,
    [CPCAcctNbr]                VARCHAR (50)  NULL,
    [CPCSiteNbr]                VARCHAR (50)  NULL,
    [CPCContractNbr]            VARCHAR (50)  NULL,
    [CPCInductionNbr]           VARCHAR (50)  NULL,
    [CPCUsername]               VARCHAR (255) NULL,
    [CPCpwd]                    VARCHAR (255) NULL,
    [PPSTAcctNbr]               VARCHAR (255) NULL,
    [PPSTTransitDays]           INT           NULL,
    [PPSTInductionAddress]      VARCHAR (255) NULL,
    [PPSTInductionCity]         VARCHAR (255) NULL,
    [PPSTInductionState]        VARCHAR (255) NULL,
    [PPSTInductionZip]          VARCHAR (25)  NULL,
    [PPSTInductionCountry]      VARCHAR (25)  NULL,
    [UpdatedBy]                 VARCHAR (100) NULL,
    [UpdatedOn]                 DATETIME      NULL,
    [CreatedBy]                 VARCHAR (100) NULL,
    [CreatedOn]                 DATETIME      NULL,
    [ActiveFlag]                BIT           NULL,
    [CourierInductionDesc]      VARCHAR (255) NULL,
    [PPSTInductionDesc]         VARCHAR (255) NULL,
    [LTLPinPrefix]              VARCHAR (25)  NULL,
    [LTLAutomatedFlag]          BIT           NULL,
    [CourierSandboxFTPusername] VARCHAR (255) NULL,
    [CourierSandboxFTPpwd]      VARCHAR (255) NULL,
    [CourierFTPCustOwnFlag]     BIT           NULL,
    [PPSTRoute]                 VARCHAR (500) NULL,
    [PPlusAcctNbr]              VARCHAR (255) NULL,
    [PPlusTransitDays]          INT           NULL,
    [PPlusInductionAddress]     VARCHAR (255) NULL,
    [PPlusInductionCity]        VARCHAR (255) NULL,
    [PPlusInductionState]       VARCHAR (255) NULL,
    [PPlusInductionZip]         VARCHAR (25)  NULL,
    [PPlusInductionCountry]     VARCHAR (25)  NULL,
    [ShipRecordType]            VARCHAR (50)  NULL,
    [PPlusInductionDesc]        VARCHAR (255) NULL,
    CONSTRAINT [PK_tblDiscoveryRequestDetails] PRIMARY KEY CLUSTERED ([idRequestDetails] ASC)
);

