CREATE TABLE [dbo].[tblDiscoveryRequest_Archive] (
    [idRequest_Archive]  INT            IDENTITY (1, 1) NOT NULL,
    [idRequest]          INT            NOT NULL,
    [TableAction]        VARCHAR (50)   NOT NULL,
    [isNewRequest]       BIT            NULL,
    [SalesRepName]       VARCHAR (255)  NULL,
    [SalesRepEmail]      VARCHAR (255)  NULL,
    [idOnboardingPhase]  INT            NULL,
    [District]           VARCHAR (255)  NULL,
    [CustomerName]       VARCHAR (255)  NULL,
    [Address]            VARCHAR (255)  NULL,
    [City]               VARCHAR (255)  NULL,
    [State]              VARCHAR (255)  NULL,
    [Zipcode]            VARCHAR (255)  NULL,
    [Country]            VARCHAR (255)  NULL,
    [Commodity]          VARCHAR (255)  NULL,
    [ProjectedRevenue]   MONEY          NULL,
    [CustomerBusContact] VARCHAR (255)  NULL,
    [CustomerBusTitle]   VARCHAR (255)  NULL,
    [CustomerBusEmail]   VARCHAR (255)  NULL,
    [CustomerBusPhone]   VARCHAR (255)  NULL,
    [CustomerITContact]  VARCHAR (255)  NULL,
    [CustomerITTitle]    VARCHAR (255)  NULL,
    [CustomerITEmail]    VARCHAR (255)  NULL,
    [CustomerITPhone]    VARCHAR (255)  NULL,
    [CurrentSolution]    VARCHAR (3000) NULL,
    [ProposedCustoms]    VARCHAR (2000) NULL,
    [CallDate1]          DATETIME       NULL,
    [CallDate2]          DATETIME       NULL,
    [CallDate3]          DATETIME       NULL,
    [UpdatedBy]          VARCHAR (100)  NULL,
    [UpdatedOn]          DATETIME       NULL,
    [CreatedBy]          VARCHAR (100)  NULL,
    [CreatedOn]          DATETIME       NULL,
    [ActiveFlag]         BIT            NULL,
    [SalesComments]      VARCHAR (3000) NULL,
    [idITBA]             INT            NULL,
    [idShippingChannel]  INT            NULL,
    [TargetGoLive]       DATETIME       NULL,
    [ActualGoLive]       DATETIME       NULL,
    [SolutionSummary]    VARCHAR (3000) NULL,
    [CustomerWebsite]    VARCHAR (500)  NULL,
    [Branch]             NVARCHAR (50)  NULL,
    [idVendor]           INT            NULL,
    [worldpakFlag]       BIT            NULL,
    [thirdpartyFlag]     BIT            NULL,
    [customFlag]         BIT            NULL,
    [CloseReason]        VARCHAR (255)  NULL,
    [DataScrubFlag]      BIT            NULL,
    [StrategicFlag]      BIT            NULL,
    [CurrentGoLive]      DATETIME       NULL,
    CONSTRAINT [PK_tblDiscoveryRequest_Archive] PRIMARY KEY CLUSTERED ([idRequest_Archive] ASC)
);

