CREATE TABLE [dbo].[tblShippingChannelAccounts] (
    [photos]                                     NVARCHAR (255) NULL,
    [Customer (Account Name)]                    NVARCHAR (255) NULL,
    [Migration Specialist]                       NVARCHAR (255) NULL,
    [Segment]                                    NVARCHAR (255) NULL,
    [Status]                                     NVARCHAR (255) NULL,
    [Account#]                                   FLOAT (53)     NULL,
    [Account Type]                               NVARCHAR (255) NULL,
    [Current Shipping Channel]                   NVARCHAR (255) NULL,
    [Current Platform]                           NVARCHAR (255) NULL,
    [Future Shipping Channel]                    NVARCHAR (255) NULL,
    [Future Platform]                            NVARCHAR (255) NULL,
    [Target Date]                                NVARCHAR (255) NULL,
    [Scheduled Date]                             NVARCHAR (255) NULL,
    [Legacy Contract]                            FLOAT (53)     NULL,
    [SAP Contract]                               NVARCHAR (255) NULL,
    [Configure OLS3 production profile (Y/N]     NVARCHAR (255) NULL,
    [Address Book]                               NVARCHAR (255) NULL,
    [Customs Items]                              NVARCHAR (255) NULL,
    [Custom Dimensions]                          NVARCHAR (255) NULL,
    [Custom Export File]                         NVARCHAR (255) NULL,
    [Ghost Scan]                                 NVARCHAR (255) NULL,
    [Customs Clearance Type ((PASS, PARS , N/A)] NVARCHAR (255) NULL,
    [Old Pin Prefix]                             NVARCHAR (255) NULL,
    [New Pin Prefix]                             NVARCHAR (255) NULL,
    [OLS2 Acct #]                                FLOAT (53)     NULL,
    [OLS3 Acct #]                                FLOAT (53)     NULL,
    [EDI Y/N]                                    NVARCHAR (255) NULL,
    [Inactivate OLS2 customer profile]           NVARCHAR (255) NULL,
    [Active or Closed (in SAP) Account]          NVARCHAR (255) NULL
);

