CREATE TABLE [dbo].[tblShippingChannelAccount] (
    [Cust_Number]                                                      NVARCHAR (255) NULL,
    [Customer (Account Name)]                                          NVARCHAR (255) NULL,
    [Migration Specialist]                                             NVARCHAR (255) NULL,
    [Technical Consultant]                                             NVARCHAR (255) NULL,
    [Segment]                                                          NVARCHAR (255) NULL,
    [Account#]                                                         FLOAT (53)     NULL,
    [Account Type]                                                     NVARCHAR (255) NULL,
    [Current Shipping Channel]                                         NVARCHAR (255) NULL,
    [Current Platform]                                                 NVARCHAR (255) NULL,
    [Future Shipping Channel]                                          NVARCHAR (255) NULL,
    [Future Platform]                                                  NVARCHAR (255) NULL,
    [Planned Start Date]                                               DATETIME       NULL,
    [Planned Customer Approval Date]                                   DATETIME       NULL,
    [Planned Migration Target Date]                                    DATETIME       NULL,
    [Scheduled Migration Date]                                         DATETIME       NULL,
    [Legacy Contract]                                                  FLOAT (53)     NULL,
    [SAP Contract]                                                     FLOAT (53)     NULL,
    [Future Migrate Date]                                              DATETIME       NULL,
    [Data Distribution Available Date]                                 DATETIME       NULL,
    [Configure OLS3 production profile (Y/N]                           NVARCHAR (255) NULL,
    [Address Book]                                                     NVARCHAR (255) NULL,
    [Customs Items]                                                    NVARCHAR (255) NULL,
    [Custom Dimensions]                                                NVARCHAR (255) NULL,
    [Custom Export File]                                               NVARCHAR (255) NULL,
    [Ghost Scan]                                                       NVARCHAR (255) NULL,
    [Customs Clearance Type ((PASS, PARS , N/A)]                       NVARCHAR (255) NULL,
    [Old Pin Prefix]                                                   NVARCHAR (255) NULL,
    [New Pin Prefix]                                                   NVARCHAR (255) NULL,
    [OLS2 Acct #]                                                      FLOAT (53)     NULL,
    [OLS3 Acct #]                                                      FLOAT (53)     NULL,
    [Implementation File Created Y/N]                                  NVARCHAR (255) NULL,
    [EDI Y/N]                                                          NVARCHAR (255) NULL,
    [EDI Shipment Status]                                              NVARCHAR (255) NULL,
    [EDI Shipment Inquiry]                                             NVARCHAR (255) NULL,
    [US Intransit Scan Required]                                       NVARCHAR (255) NULL,
    [Technical Call - Solution Selection (Date)]                       NVARCHAR (255) NULL,
    [New World EDI specs provided to customer EDI contact (Date)]      NVARCHAR (255) NULL,
    [Gain approval from customer (Date)]                               NVARCHAR (255) NULL,
    [Technical Solution Implementation / Production Readiness Confirm] NVARCHAR (255) NULL,
    [Future migrate accounts in SAP (set Acct_at_Cust date to M minus] DATETIME       NULL,
    [Create technical setup EDI documents (Shipment status, electroni] NVARCHAR (255) NULL,
    [Host customer training (Date)]                                    NVARCHAR (255) NULL,
    [Migration (Date)]                                                 DATETIME       NULL,
    [Production Compliance -Landing Test (Date)]                       NVARCHAR (255) NULL,
    [Deactivate Legacy setup - 30 days (Date)]                         NVARCHAR (255) NULL,
    [Inactivate OLS2 customer profile]                                 NVARCHAR (255) NULL,
    [Finish Line - Migration Complete (Date)]                          DATETIME       NULL,
    [Active or Closed (in SAP) Account]                                NVARCHAR (255) NULL
);

