//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeaconARAcc
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAccount { get; set; }
        public string CustomerAccountBI { get; set; }
        public string Control { get; set; }
        public Nullable<decimal> AmountUSD { get; set; }
        public Nullable<System.DateTime> HAWBDate { get; set; }
        public Nullable<System.DateTime> FinalizedDate { get; set; }
        public string BilledCurrency { get; set; }
        public string ProductType { get; set; }
        public string ServiceType { get; set; }
        public string Accessorial { get; set; }
        public string Source { get; set; }
        public Nullable<decimal> AmountCAD { get; set; }
        public bool IsAccrual { get; set; }
        public Nullable<System.DateTime> BillingClosingDate { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Category { get; set; }
    }
}
