//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_tblInvoices_Backup_09202016
    {
        public int idInvoice { get; set; }
        public string VendorNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> InvoiceAmt { get; set; }
        public string Currency { get; set; }
        public string EnteredBy { get; set; }
        public Nullable<System.DateTime> DateEntered { get; set; }
        public Nullable<System.DateTime> AppendDate { get; set; }
        public Nullable<int> invapp { get; set; }
        public Nullable<System.DateTime> BBAScanDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> FundingDate { get; set; }
        public Nullable<System.DateTime> Submitted { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string Source { get; set; }
        public string CarrierName { get; set; }
    }
}
