//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class exp_tblServiceTypesNEW
    {
        public int idServiceType { get; set; }
        public string Service_Code { get; set; }
        public string Service_Desc { get; set; }
        public string Service_Group_Name { get; set; }
        public string Service_Group_Desc { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string ExcludeFlag { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
