//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PI_Customers
    {
        public Nullable<double> ID { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string PhoneNbr { get; set; }
        public string Contact { get; set; }
        public string ApptNbr { get; set; }
        public string ApptRequired { get; set; }
        public Nullable<double> CountryID { get; set; }
        public string FAXNbr { get; set; }
        public string ApptContact { get; set; }
        public Nullable<double> Residential { get; set; }
        public Nullable<double> Liftgate { get; set; }
        public Nullable<double> Inside { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string SalesRep { get; set; }
        public Nullable<double> BillToID { get; set; }
        public string CreditStatus { get; set; }
        public string CloseTime { get; set; }
        public Nullable<double> LocationID { get; set; }
        public Nullable<double> CreditLimit { get; set; }
        public string Website { get; set; }
        public Nullable<double> PODonInvoice { get; set; }
        public string CreditAppDate { get; set; }
        public string CollectionContact { get; set; }
        public string CollectionPhoneNbr { get; set; }
        public string NextCallDate { get; set; }
        public Nullable<double> CreditAppOnFile { get; set; }
        public Nullable<System.DateTime> LastSaleDate { get; set; }
        public Nullable<System.DateTime> LastPaidDate { get; set; }
        public string LastCheckNbr { get; set; }
        public Nullable<double> HighestBalance { get; set; }
        public Nullable<double> Balance0_30 { get; set; }
        public Nullable<double> Balance30_60 { get; set; }
        public Nullable<double> Balance60_90 { get; set; }
        public Nullable<double> Balance90Plus { get; set; }
        public Nullable<double> AvgDaysToPay { get; set; }
        public string Collector { get; set; }
        public Nullable<double> InActive { get; set; }
        public string Remarks { get; set; }
        public Nullable<double> Consolidation { get; set; }
        public Nullable<double> SDAppointment { get; set; }
        public string FAXCollectNbr { get; set; }
        public string WeightDefault { get; set; }
        public string FederalIDNbr { get; set; }
        public string GSTNbr { get; set; }
        public Nullable<double> DimWtValue { get; set; }
        public string EDIPartnerID { get; set; }
        public string Control { get; set; }
        public string SecurityValidation { get; set; }
        public bool PODRequired { get; set; }
        public Nullable<double> InvoicingException { get; set; }
        public Nullable<double> KnownShipper { get; set; }
        public string RevalidationDate { get; set; }
        public string TSAValidationNbr { get; set; }
        public string BrokerID { get; set; }
        public string OpenTime { get; set; }
        public Nullable<double> Liability { get; set; }
        public string DefaultAgentID { get; set; }
        public Nullable<double> CommHold { get; set; }
        public Nullable<double> CommHoldPct { get; set; }
        public string CommHoldDays { get; set; }
        public Nullable<double> GlobalAccount { get; set; }
        public string InvoiceRemarks { get; set; }
        public string PURemarks { get; set; }
        public Nullable<double> InvoiceExceptionPeriod { get; set; }
        public Nullable<double> FamilyCodeID { get; set; }
        public string InvoiceType { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string Account { get; set; }
        public string BillTo { get; set; }
        public Nullable<double> InvoiceExceptionTypeID { get; set; }
        public Nullable<double> SalesRepID { get; set; }
        public string AddedBy { get; set; }
        public string SubAddress1 { get; set; }
        public string SubZip { get; set; }
        public string SOPDocName { get; set; }
        public string Terms { get; set; }
        public string CurrencyBillingDefault { get; set; }
        public string CurrencyEntryDefault { get; set; }
        public Nullable<double> PrintBeyondDelZoneOnInvoice { get; set; }
        public string EDIStatusMessageMethodID { get; set; }
        public string EDIInvoiceMessageMethodID { get; set; }
        public string EDILoadResponseMessageMethodID { get; set; }
        public Nullable<double> IsInductionCenter { get; set; }
        public Nullable<double> IsGateway { get; set; }
        public Nullable<double> AllInBilling { get; set; }
        public Nullable<double> UsePHawb { get; set; }
        public Nullable<double> CanadianClearanceTypeID { get; set; }
        public Nullable<double> fcBalance0_30 { get; set; }
        public Nullable<double> fcBalance30_60 { get; set; }
        public Nullable<double> fcBalance60_90 { get; set; }
        public Nullable<double> fcBalance90Plus { get; set; }
        public Nullable<double> AutoInvReprint { get; set; }
        public string DiscountTier { get; set; }
        public string CollectionNotes { get; set; }
        public Nullable<double> SalesLead { get; set; }
        public string IndustryID { get; set; }
    }
}
