//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PurolatorReportingEntities : DbContext
    {
        public PurolatorReportingEntities()
            : base("name=PurolatorReportingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<BeaconAR> BeaconAR { get; set; }
        public virtual DbSet<BeaconARAcc> BeaconARAcc { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<LookupProductsBI> LookupProductsBI { get; set; }
        public virtual DbSet<LookupProductsBIAccessorials> LookupProductsBIAccessorials { get; set; }
        public virtual DbSet<LookupProductsGL> LookupProductsGL { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_dailytasks> tbl_dailytasks { get; set; }
        public virtual DbSet<tbl_projects> tbl_projects { get; set; }
        public virtual DbSet<tblAccessorials> tblAccessorials { get; set; }
        public virtual DbSet<tblAccessorials_Archive> tblAccessorials_Archive { get; set; }
        public virtual DbSet<tblAccessorialType> tblAccessorialType { get; set; }
        public virtual DbSet<tblAccessorialType_Archive> tblAccessorialType_Archive { get; set; }
        public virtual DbSet<tblAccountAddressType> tblAccountAddressType { get; set; }
        public virtual DbSet<tblAccountAddressType_Archive> tblAccountAddressType_Archive { get; set; }
        public virtual DbSet<tblAccountContactType> tblAccountContactType { get; set; }
        public virtual DbSet<tblAccountContactType_Archive> tblAccountContactType_Archive { get; set; }
        public virtual DbSet<tblAccountingCodes> tblAccountingCodes { get; set; }
        public virtual DbSet<tblAccountingCodes_Archive> tblAccountingCodes_Archive { get; set; }
        public virtual DbSet<tblAccountingCodeType> tblAccountingCodeType { get; set; }
        public virtual DbSet<tblAccountingCodeType_Archive> tblAccountingCodeType_Archive { get; set; }
        public virtual DbSet<tblAccountMargins> tblAccountMargins { get; set; }
        public virtual DbSet<tblAccountMargins_Archive> tblAccountMargins_Archive { get; set; }
        public virtual DbSet<tblAccounts> tblAccounts { get; set; }
        public virtual DbSet<tblAccounts_Archive> tblAccounts_Archive { get; set; }
        public virtual DbSet<tblAccountTargets> tblAccountTargets { get; set; }
        public virtual DbSet<tblAccountTargets_Archive> tblAccountTargets_Archive { get; set; }
        public virtual DbSet<tblAddressType> tblAddressType { get; set; }
        public virtual DbSet<tblAddressType_Archive> tblAddressType_Archive { get; set; }
        public virtual DbSet<tblBusinessType> tblBusinessType { get; set; }
        public virtual DbSet<tblBusinessType_Archive> tblBusinessType_Archive { get; set; }
        public virtual DbSet<tblCertificates> tblCertificates { get; set; }
        public virtual DbSet<tblCertificates_Archive> tblCertificates_Archive { get; set; }
        public virtual DbSet<tblClientAddresses> tblClientAddresses { get; set; }
        public virtual DbSet<tblClientAddresses_Archive> tblClientAddresses_Archive { get; set; }
        public virtual DbSet<tblClientAddressTypes> tblClientAddressTypes { get; set; }
        public virtual DbSet<tblClientAddressTypes_Archive> tblClientAddressTypes_Archive { get; set; }
        public virtual DbSet<tblClientContacts> tblClientContacts { get; set; }
        public virtual DbSet<tblClientContacts_Archive> tblClientContacts_Archive { get; set; }
        public virtual DbSet<tblClientContactType> tblClientContactType { get; set; }
        public virtual DbSet<tblClients> tblClients { get; set; }
        public virtual DbSet<tblClients_Archive> tblClients_Archive { get; set; }
        public virtual DbSet<tblCommissionBasis> tblCommissionBasis { get; set; }
        public virtual DbSet<tblCommissionDetail> tblCommissionDetail { get; set; }
        public virtual DbSet<tblCommissionPlan> tblCommissionPlan { get; set; }
        public virtual DbSet<tblContactType> tblContactType { get; set; }
        public virtual DbSet<tblContactType_Archive> tblContactType_Archive { get; set; }
        public virtual DbSet<tblContractAddressType> tblContractAddressType { get; set; }
        public virtual DbSet<tblContractAddressType_Archive> tblContractAddressType_Archive { get; set; }
        public virtual DbSet<tblContractContactType> tblContractContactType { get; set; }
        public virtual DbSet<tblContractContactType_Archive> tblContractContactType_Archive { get; set; }
        public virtual DbSet<tblContracts> tblContracts { get; set; }
        public virtual DbSet<tblContracts_Archive> tblContracts_Archive { get; set; }
        public virtual DbSet<tblCostCenters> tblCostCenters { get; set; }
        public virtual DbSet<tblCostCenters_Archive> tblCostCenters_Archive { get; set; }
        public virtual DbSet<tblCountries> tblCountries { get; set; }
        public virtual DbSet<tblCountries_Archive> tblCountries_Archive { get; set; }
        public virtual DbSet<tblCurrencyCodes> tblCurrencyCodes { get; set; }
        public virtual DbSet<tblCurrencyCodes_Archive> tblCurrencyCodes_Archive { get; set; }
        public virtual DbSet<tblDistricts> tblDistricts { get; set; }
        public virtual DbSet<tblDistricts_Archive> tblDistricts_Archive { get; set; }
        public virtual DbSet<tblEmployee> tblEmployee { get; set; }
        public virtual DbSet<tblEmployee_0130NG> tblEmployee_0130NG { get; set; }
        public virtual DbSet<tblEmployee_Archive> tblEmployee_Archive { get; set; }
        public virtual DbSet<tblEmployeeCertifications> tblEmployeeCertifications { get; set; }
        public virtual DbSet<tblEmployeeCertifications_Archive> tblEmployeeCertifications_Archive { get; set; }
        public virtual DbSet<tblEmployeeFunction> tblEmployeeFunction { get; set; }
        public virtual DbSet<tblEmployeeFunction_Archive> tblEmployeeFunction_Archive { get; set; }
        public virtual DbSet<tblEmployeeNG> tblEmployeeNG { get; set; }
        public virtual DbSet<tblExchangeRates> tblExchangeRates { get; set; }
        public virtual DbSet<tblExchangeRates_Archive> tblExchangeRates_Archive { get; set; }
        public virtual DbSet<tblHolidayDefinitions> tblHolidayDefinitions { get; set; }
        public virtual DbSet<tblManagerLevel> tblManagerLevel { get; set; }
        public virtual DbSet<tblManagerLevel_Archive> tblManagerLevel_Archive { get; set; }
        public virtual DbSet<tblMeasurementUnit> tblMeasurementUnit { get; set; }
        public virtual DbSet<tblMeasurementUnit_Archive> tblMeasurementUnit_Archive { get; set; }
        public virtual DbSet<tblPayoutFrequency> tblPayoutFrequency { get; set; }
        public virtual DbSet<tblPI_ApplicationDepartment> tblPI_ApplicationDepartment { get; set; }
        public virtual DbSet<tblPI_ApplicationDepartment_Archive> tblPI_ApplicationDepartment_Archive { get; set; }
        public virtual DbSet<tblPI_ApplicationDistrictRestriction> tblPI_ApplicationDistrictRestriction { get; set; }
        public virtual DbSet<tblPI_ApplicationException> tblPI_ApplicationException { get; set; }
        public virtual DbSet<tblPI_ApplicationRegionRestriction> tblPI_ApplicationRegionRestriction { get; set; }
        public virtual DbSet<tblPI_ApplicationReportArchives> tblPI_ApplicationReportArchives { get; set; }
        public virtual DbSet<tblPI_ApplicationReportRoles> tblPI_ApplicationReportRoles { get; set; }
        public virtual DbSet<tblPI_ApplicationReports> tblPI_ApplicationReports { get; set; }
        public virtual DbSet<tblPI_ApplicationRoles> tblPI_ApplicationRoles { get; set; }
        public virtual DbSet<tblPI_ApplicationRoles_Archive> tblPI_ApplicationRoles_Archive { get; set; }
        public virtual DbSet<tblPI_Applications> tblPI_Applications { get; set; }
        public virtual DbSet<tblPI_Applications_Archive> tblPI_Applications_Archive { get; set; }
        public virtual DbSet<tblPI_ApplicationSRIDRestriction> tblPI_ApplicationSRIDRestriction { get; set; }
        public virtual DbSet<tblPI_ApplicationUser> tblPI_ApplicationUser { get; set; }
        public virtual DbSet<tblPI_ApplicationUser_Archive> tblPI_ApplicationUser_Archive { get; set; }
        public virtual DbSet<tblPI_ApplicationUserRole> tblPI_ApplicationUserRole { get; set; }
        public virtual DbSet<tblPI_ApplicationUserRole_Archive> tblPI_ApplicationUserRole_Archive { get; set; }
        public virtual DbSet<tblPI_DepartmentMember> tblPI_DepartmentMember { get; set; }
        public virtual DbSet<tblPI_DepartmentMember_Archive> tblPI_DepartmentMember_Archive { get; set; }
        public virtual DbSet<tblPI_Departments> tblPI_Departments { get; set; }
        public virtual DbSet<tblPI_Departments_Archive> tblPI_Departments_Archive { get; set; }
        public virtual DbSet<tblPI_ReportType> tblPI_ReportType { get; set; }
        public virtual DbSet<tblProductGroup> tblProductGroup { get; set; }
        public virtual DbSet<tblProductGroup_Archive> tblProductGroup_Archive { get; set; }
        public virtual DbSet<tblProductName> tblProductName { get; set; }
        public virtual DbSet<tblProductName_Archive> tblProductName_Archive { get; set; }
        public virtual DbSet<tblRegions> tblRegions { get; set; }
        public virtual DbSet<tblRegions_Archive> tblRegions_Archive { get; set; }
        public virtual DbSet<tblRevenueTypes> tblRevenueTypes { get; set; }
        public virtual DbSet<tblRevenueTypes_Archive> tblRevenueTypes_Archive { get; set; }
        public virtual DbSet<tblSalesDepartment> tblSalesDepartment { get; set; }
        public virtual DbSet<tblSalesDepartment_Archive> tblSalesDepartment_Archive { get; set; }
        public virtual DbSet<tblSalesDepartmentMember> tblSalesDepartmentMember { get; set; }
        public virtual DbSet<tblSalesDepartmentMember_Archive> tblSalesDepartmentMember_Archive { get; set; }
        public virtual DbSet<tblSalesManager> tblSalesManager { get; set; }
        public virtual DbSet<tblSalesManager_Archive> tblSalesManager_Archive { get; set; }
        public virtual DbSet<tblSalesRep> tblSalesRep { get; set; }
        public virtual DbSet<tblSalesRep_Archive> tblSalesRep_Archive { get; set; }
        public virtual DbSet<tblSalesRepAccounts> tblSalesRepAccounts { get; set; }
        public virtual DbSet<tblSalesRepAccounts_Archive> tblSalesRepAccounts_Archive { get; set; }
        public virtual DbSet<tblSalesRepDefaultTarget> tblSalesRepDefaultTarget { get; set; }
        public virtual DbSet<tblSalesRepDefaultTarget_Archive> tblSalesRepDefaultTarget_Archive { get; set; }
        public virtual DbSet<tblSalesRoles> tblSalesRoles { get; set; }
        public virtual DbSet<tblSalesRoles_Archive> tblSalesRoles_Archive { get; set; }
        public virtual DbSet<tblSalesTeam> tblSalesTeam { get; set; }
        public virtual DbSet<tblSalesTeam_Archive> tblSalesTeam_Archive { get; set; }
        public virtual DbSet<tblSalesTypes> tblSalesTypes { get; set; }
        public virtual DbSet<tblSalesTypes_Archive> tblSalesTypes_Archive { get; set; }
        public virtual DbSet<tblScheduledProcess> tblScheduledProcess { get; set; }
        public virtual DbSet<tblScheduledProcessLog> tblScheduledProcessLog { get; set; }
        public virtual DbSet<tblScheduledProcessLogFile> tblScheduledProcessLogFile { get; set; }
        public virtual DbSet<tblScheduledProcessSchedule> tblScheduledProcessSchedule { get; set; }
        public virtual DbSet<tblServiceGroupType> tblServiceGroupType { get; set; }
        public virtual DbSet<tblServiceGroupType_Archive> tblServiceGroupType_Archive { get; set; }
        public virtual DbSet<tblServiceType> tblServiceType { get; set; }
        public virtual DbSet<tblServiceType_Archive> tblServiceType_Archive { get; set; }
        public virtual DbSet<tblServiceTypeGroups> tblServiceTypeGroups { get; set; }
        public virtual DbSet<tblServiceTypeGroups_Archive> tblServiceTypeGroups_Archive { get; set; }
        public virtual DbSet<tblTransactions> tblTransactions { get; set; }
        public virtual DbSet<tblTransactions_Archive> tblTransactions_Archive { get; set; }
        public virtual DbSet<tblTransactionTypes> tblTransactionTypes { get; set; }
        public virtual DbSet<tblTransactionTypes_Archive> tblTransactionTypes_Archive { get; set; }
        public virtual DbSet<exp_tblInvoices_Backup_09202016> exp_tblInvoices_Backup_09202016 { get; set; }
        public virtual DbSet<exp_tblServiceTypes> exp_tblServiceTypes { get; set; }
        public virtual DbSet<exp_tblServiceTypesNEW> exp_tblServiceTypesNEW { get; set; }
        public virtual DbSet<PI_Customers> PI_Customers { get; set; }
        public virtual DbSet<tbl_migratedTables> tbl_migratedTables { get; set; }
        public virtual DbSet<tbl_typeofrequests> tbl_typeofrequests { get; set; }
        public virtual DbSet<tblAccountImport> tblAccountImport { get; set; }
        public virtual DbSet<tblEmployee_backup_03152017> tblEmployee_backup_03152017 { get; set; }
        public virtual DbSet<tblEmployee_backup_09272016> tblEmployee_backup_09272016 { get; set; }
        public virtual DbSet<tblEmployee_Updated_03202017> tblEmployee_Updated_03202017 { get; set; }
        public virtual DbSet<tblPI_ApplicationUser_backup> tblPI_ApplicationUser_backup { get; set; }
        public virtual DbSet<tblPI_ApplicationUserRole_backup> tblPI_ApplicationUserRole_backup { get; set; }
        public virtual DbSet<tblSalesRepCodes> tblSalesRepCodes { get; set; }
        public virtual DbSet<tblSAPFileBICodes> tblSAPFileBICodes { get; set; }
        public virtual DbSet<tblSource> tblSource { get; set; }
    }
}
