//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_typeofrequests
    {
        public int RequestId { get; set; }
        public string TypeofRequest { get; set; }
        public string Description { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
