//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAccounts()
        {
            this.tblAccountContactType = new HashSet<tblAccountContactType>();
            this.tblAccountMargins = new HashSet<tblAccountMargins>();
            this.tblAccountTargets = new HashSet<tblAccountTargets>();
            this.tblSalesRepAccounts = new HashSet<tblSalesRepAccounts>();
            this.tblTransactions = new HashSet<tblTransactions>();
        }
    
        public int idAccount { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public int idContract { get; set; }
        public int idRegion { get; set; }
        public string DataSource { get; set; }
        public string BIAccount { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountContactType> tblAccountContactType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountMargins> tblAccountMargins { get; set; }
        public virtual tblContracts tblContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAccountTargets> tblAccountTargets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesRepAccounts> tblSalesRepAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTransactions> tblTransactions { get; set; }
    }
}
