//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountImport
    {
        public string Account { get; set; }
        public string Customer { get; set; }
        public string Branch { get; set; }
        public Nullable<double> Cost_Center { get; set; }
        public string Business_Type { get; set; }
        public string Strategic_SRID { get; set; }
        public string Local_SRID { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
