//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountingCodes_Archive
    {
        public int idAccountingCode_Archive { get; set; }
        public string TableAction { get; set; }
        public int idAccountingCode { get; set; }
        public string AccountingCode { get; set; }
        public string CodeDescription { get; set; }
        public bool IsActive { get; set; }
        public int idAccountingCodeType { get; set; }
        public int idBeacon { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
