//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccessorials
    {
        public int idAccessorial { get; set; }
        public int AccessorialCode { get; set; }
        public string AccessorialName { get; set; }
        public int idAccessorialType { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblAccessorialType tblAccessorialType { get; set; }
    }
}
