//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccounts_Archive
    {
        public int idAccount_Archive { get; set; }
        public string TableAction { get; set; }
        public int idAccount { get; set; }
        public string AccountNumber { get; set; }
        public string AccountName { get; set; }
        public int idContract { get; set; }
        public Nullable<int> idRegion { get; set; }
        public string DataSource { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
