//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClientAddressTypes_Archive
    {
        public int idClientAddressType_Archive { get; set; }
        public string TableAction { get; set; }
        public int idClientAddressType { get; set; }
        public int idClientAddress { get; set; }
        public int idAddressType { get; set; }
        public bool IsPrimary { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    }
}
