//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCommissionDetail
    {
        public int idCommissionDetail { get; set; }
        public int idCommissionPlan { get; set; }
        public int idCommissionBasis { get; set; }
        public int idPayoutFrequency { get; set; }
        public double StartRange { get; set; }
        public double EndRange { get; set; }
        public double PayoutVariableAmount { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
