//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCurrencyCodes_Archive
    {
        public int idCurrencyCode_Archive { get; set; }
        public string TableAction { get; set; }
        public int idCurrencyCode { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyName { get; set; }
        public int idCountry { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
