//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeFunction_Archive
    {
        public int idEmployeeFunction_Archive { get; set; }
        public string TableAction { get; set; }
        public int idEmployeeFunction { get; set; }
        public string FunctionCode { get; set; }
        public string FunctionDecription { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
