//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeCertifications
    {
        public int idEmployeeCertifications { get; set; }
        public int idEmployee { get; set; }
        public int idCertification { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CertificationNumber { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblCertificates tblCertificates { get; set; }
        public virtual tblEmployee_0130NG tblEmployee_0130NG { get; set; }
    }
}
