//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHolidayDefinitions
    {
        public int idHolidayDefinition { get; set; }
        public string HolidayName { get; set; }
        public System.DateTime StaticDate { get; set; }
        public string CalculationMethod { get; set; }
        public string ObservenceMethod { get; set; }
        public bool IsInternational { get; set; }
        public bool IsAnnual { get; set; }
        public string CountryCode { get; set; }
        public string ProvinceCode { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
