//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationReportArchives
    {
        public int idPI_ApplicationReportArchive { get; set; }
        public int idPI_ApplicationReport { get; set; }
        public string ReportName { get; set; }
        public System.DateTime ReportDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string FileName { get; set; }
        public string ProcessName { get; set; }
        public string ProcessParameters { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblPI_ApplicationReports tblPI_ApplicationReports { get; set; }
    }
}
