//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPI_ApplicationReports()
        {
            this.tblPI_ApplicationReportArchives = new HashSet<tblPI_ApplicationReportArchives>();
            this.tblPI_ApplicationReportRoles = new HashSet<tblPI_ApplicationReportRoles>();
        }
    
        public int idPI_ApplicationReport { get; set; }
        public int idPI_Application { get; set; }
        public int idPI_ReportType { get; set; }
        public string ReportName { get; set; }
        public string ArchiveFolder { get; set; }
        public bool UseMonthlyIncrement { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationReportArchives> tblPI_ApplicationReportArchives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationReportRoles> tblPI_ApplicationReportRoles { get; set; }
        public virtual tblPI_Applications tblPI_Applications { get; set; }
        public virtual tblPI_ReportType tblPI_ReportType { get; set; }
    }
}
