//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationUserRole_Archive
    {
        public int idPI_ApplicationUserRole_Archive { get; set; }
        public string TableAction { get; set; }
        public int idPI_ApplicationUserRole { get; set; }
        public int idPI_ApplicationUser { get; set; }
        public int idPI_ApplicationRole { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
