//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationReportRoles
    {
        public int idPI_ApplicationReportRole { get; set; }
        public int idPI_ApplicationReport { get; set; }
        public int idPI_ApplicationRole { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblPI_ApplicationReports tblPI_ApplicationReports { get; set; }
        public virtual tblPI_ApplicationRoles tblPI_ApplicationRoles { get; set; }
    }
}
