//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationException
    {
        public int idPI_ApplicationException { get; set; }
        public int idPI_Application { get; set; }
        public string ExceptionCode { get; set; }
        public string ExceptionMessage { get; set; }
        public string FileName { get; set; }
        public Nullable<int> ErrorRow { get; set; }
        public Nullable<int> ErrorColumn { get; set; }
        public Nullable<int> idScheduledProcessLog { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblPI_Applications tblPI_Applications { get; set; }
    }
}
