//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_ApplicationUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPI_ApplicationUser()
        {
            this.tblPI_ApplicationUserRole = new HashSet<tblPI_ApplicationUserRole>();
        }
    
        public int idPI_ApplicationUser { get; set; }
        public int idPI_Application { get; set; }
        public int idEmployee { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string EncryptedPassword { get; set; }
        public string Password { get; set; }
    
        public virtual tblPI_Applications tblPI_Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationUserRole> tblPI_ApplicationUserRole { get; set; }
    }
}
