//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPI_Applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPI_Applications()
        {
            this.tblPI_ApplicationDepartment = new HashSet<tblPI_ApplicationDepartment>();
            this.tblPI_ApplicationException = new HashSet<tblPI_ApplicationException>();
            this.tblPI_ApplicationReports = new HashSet<tblPI_ApplicationReports>();
            this.tblPI_ApplicationRoles = new HashSet<tblPI_ApplicationRoles>();
            this.tblPI_ApplicationUser = new HashSet<tblPI_ApplicationUser>();
        }
    
        public int idPI_Application { get; set; }
        public string ApplicationName { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationDepartment> tblPI_ApplicationDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationException> tblPI_ApplicationException { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationReports> tblPI_ApplicationReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationRoles> tblPI_ApplicationRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPI_ApplicationUser> tblPI_ApplicationUser { get; set; }
    }
}
