//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRevenueTypes_Archive
    {
        public int idRevenueType_Archive { get; set; }
        public string TableAction { get; set; }
        public int idRevenueType { get; set; }
        public string TypeName { get; set; }
        public string EDICode { get; set; }
        public Nullable<int> idRevenueAccountingCode { get; set; }
        public Nullable<int> idExpenseAccountingCode { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
