//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesRep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSalesRep()
        {
            this.tblSalesDepartmentMember = new HashSet<tblSalesDepartmentMember>();
            this.tblSalesRepAccounts = new HashSet<tblSalesRepAccounts>();
            this.tblSalesRepDefaultTarget = new HashSet<tblSalesRepDefaultTarget>();
        }
    
        public int idSalesRep { get; set; }
        public string SalesRepCode { get; set; }
        public int idEmployee { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public Nullable<int> idSalesTeam { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblEmployee_0130NG tblEmployee_0130NG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesDepartmentMember> tblSalesDepartmentMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesRepAccounts> tblSalesRepAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSalesRepDefaultTarget> tblSalesRepDefaultTarget { get; set; }
    }
}
