//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesRep_Archive
    {
        public int idSalesRep_Archive { get; set; }
        public string TableAction { get; set; }
        public int idSalesRep { get; set; }
        public string SalesRepCode { get; set; }
        public int idEmployee { get; set; }
        public Nullable<decimal> Threshold { get; set; }
        public Nullable<int> idSalesTeam { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
