//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesManager
    {
        public int idSalesManager { get; set; }
        public int idSalesDepartment { get; set; }
        public int idEmployee { get; set; }
        public int idManagerLevel { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblEmployee_0130NG tblEmployee_0130NG { get; set; }
        public virtual tblManagerLevel tblManagerLevel { get; set; }
        public virtual tblSalesDepartment tblSalesDepartment { get; set; }
    }
}
