//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalesRepAccounts
    {
        public int idSalesRepAccount { get; set; }
        public int idSalesRep { get; set; }
        public int idAccount { get; set; }
        public int idSalesRole { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblAccounts tblAccounts { get; set; }
        public virtual tblSalesRep tblSalesRep { get; set; }
    }
}
