//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceTypeGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblServiceTypeGroups()
        {
            this.tblServiceType = new HashSet<tblServiceType>();
        }
    
        public int idServiceTypeGroup { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public int idServiceGroupType { get; set; }
        public bool IsActive { get; set; }
        public int idBeacon { get; set; }
        public Nullable<int> BICode { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual tblServiceGroupType tblServiceGroupType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblServiceType> tblServiceType { get; set; }
    }
}
