//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroReportingEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransactions
    {
        public int idTransaction { get; set; }
        public int idAccount { get; set; }
        public int idTransactionType { get; set; }
        public int idRevenueType { get; set; }
        public int idRegion { get; set; }
        public int idServiceType { get; set; }
        public int idProductName { get; set; }
        public int idMeasurementUnit { get; set; }
        public int idCurrencyCode { get; set; }
        public System.DateTime ShipmentDate { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public int ShipmentCount { get; set; }
        public int SumOfPieces { get; set; }
        public int SumOfWeight { get; set; }
        public Nullable<int> idScheduledProcessLog { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<int> idServiceTypeGroup { get; set; }
        public Nullable<int> FiscalMonth { get; set; }
        public Nullable<int> FiscalYear { get; set; }
        public Nullable<int> idBICode { get; set; }
        public string Code { get; set; }
        public string Source { get; set; }
    
        public virtual tblAccounts tblAccounts { get; set; }
        public virtual tblMeasurementUnit tblMeasurementUnit { get; set; }
        public virtual tblRegions tblRegions { get; set; }
        public virtual tblRevenueTypes tblRevenueTypes { get; set; }
        public virtual tblServiceType tblServiceType { get; set; }
        public virtual tblTransactionTypes tblTransactionTypes { get; set; }
    }
}
