//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroTouchEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutomatedTesting
    {
        public long ID { get; set; }
        public string TestName { get; set; }
        public string Category { get; set; }
        public string Step { get; set; }
        public bool Pass { get; set; }
        public System.DateTime RunDate { get; set; }
    }
}
