//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroTouchEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiscoveryRequest_Archive
    {
        public int idRequest_Archive { get; set; }
        public int idRequest { get; set; }
        public string TableAction { get; set; }
        public Nullable<bool> isNewRequest { get; set; }
        public string SalesRepName { get; set; }
        public string SalesRepEmail { get; set; }
        public Nullable<int> idOnboardingPhase { get; set; }
        public string District { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string Commodity { get; set; }
        public Nullable<decimal> ProjectedRevenue { get; set; }
        public string CustomerBusContact { get; set; }
        public string CustomerBusTitle { get; set; }
        public string CustomerBusEmail { get; set; }
        public string CustomerBusPhone { get; set; }
        public string CustomerITContact { get; set; }
        public string CustomerITTitle { get; set; }
        public string CustomerITEmail { get; set; }
        public string CustomerITPhone { get; set; }
        public string CurrentSolution { get; set; }
        public string ProposedCustoms { get; set; }
        public Nullable<System.DateTime> CallDate1 { get; set; }
        public Nullable<System.DateTime> CallDate2 { get; set; }
        public Nullable<System.DateTime> CallDate3 { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> ActiveFlag { get; set; }
        public string SalesComments { get; set; }
        public Nullable<int> idITBA { get; set; }
        public Nullable<int> idShippingChannel { get; set; }
        public Nullable<System.DateTime> TargetGoLive { get; set; }
        public Nullable<System.DateTime> ActualGoLive { get; set; }
        public string SolutionSummary { get; set; }
        public string CustomerWebsite { get; set; }
        public string Branch { get; set; }
        public Nullable<int> idVendor { get; set; }
        public Nullable<bool> worldpakFlag { get; set; }
        public Nullable<bool> thirdpartyFlag { get; set; }
        public Nullable<bool> customFlag { get; set; }
        public string CloseReason { get; set; }
        public Nullable<bool> DataScrubFlag { get; set; }
        public Nullable<bool> StrategicFlag { get; set; }
        public Nullable<System.DateTime> CurrentGoLive { get; set; }
    }
}
