//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuroTouchEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp_tblDiscoveryRequestCustomerInfo
    {
        public int idRequest { get; set; }
        public string CustomerBusContact { get; set; }
        public string CustomerBusTitle { get; set; }
        public string CustomerBusEmail { get; set; }
        public string CustomerBusPhone { get; set; }
        public string CustomerITContact { get; set; }
        public string CustomerITTitle { get; set; }
        public string CustomerITEmail { get; set; }
        public string CustomerITPhone { get; set; }
    }
}
